### ISSUE TITLE
I clone the simple app to my pycharm then install the dependency but get error when startup

### ISSUE THREAD

**Issue by honghh2018** [django-webpack/django-webpack-loader#354]
Hi,
    I clone the simple app to my pycharm then install the dependency but get error when startup.

the below showing below:
(simple) D:\project\django_webpack\django-webpack-loader-master\examples\simple>.\node_modules\.bin\webpack --config webpack.config.js --watch

webpack is watching the files…

Hash: 66c7788cb70eebff4905
Version: webpack 4.47.0
Time: 1269ms
Built at: 2023/09/16 13:16:57
 2 assets
Entrypoint main = main-66c7788cb70eebff4905.css main-66c7788cb70eebff4905.js
[7] ./assets/css/app.css 39 bytes {0} [built]
[8] ./assets/js/index.jsx + 1 modules 374 bytes {0} [built]
    | ./assets/js/index.jsx 186 bytes [built]
    | ./assets/js/app.jsx 173 bytes [built]
    + 8 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in main-66c7788cb70eebff4905.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at D:\project\django_webpack\django-webpack-loader-master\examples\simple\node_modules\terser-webpack-plugin\dist\index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (D:\project\django_webpack\django-webpack-loader-master\examples\simple\node_modules\terser-webpack-plugin\dist\index.js:160:259)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\project\django_webpack\django-webpack-loader-master\examples\simple\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)       
    at AsyncSeriesHook.lazyCompileHook (D:\project\django_webpack\django-webpack-loader-master\examples\simple\node_modules\tapable\lib\Hook.js:154:20)
    at D:\project\django_webpack\django-webpack-loader-master\examples\simple\node_modules\webpack\lib\Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\project\django_webpack\django-webpack-loader-master\examples\simple\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)       
    at AsyncSeriesHook.lazyCompileHook (D:\project\django_webpack\django-webpack-loader-master\examples\simple\node_modules\tapable\lib\Hook.js:154:20)
    at AsyncSeriesHook.lazyCompileHook (D:\project\django_webpack\django-webpack-loader-master\examples\simple\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (D:\project\django_webpack\django-webpack-loader-master\examples\simple\node_modules\webpack\lib\Compilation.js:1253:28)
    at D:\project\django_webpack\django-webpack-loader-master\examples\simple\node_modules\webpack\lib\Compiler.js:672:17
    at eval (eval at create (D:\project\django_webpack\django-webpack-loader-master\examples\simple\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at D:\project\django_webpack\django-webpack-loader-master\examples\simple\node_modules\webpack\lib\Compilation.js:1185:12
    at D:\project\django_webpack\django-webpack-loader-master\examples\simple\node_modules\webpack\lib\Compilation.js:1097:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!assets/css/app.css:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js!./assets/css/app.css 259 bytes {0} [built]
        + 1 hidden module

![image](https://github.com/django-webpack/django-webpack-loader/assets/41668708/b70be768-9f81-4fa0-888f-00e0a00fcef7)
Best,
hanhuihong

**Comment by fjsj** [comment]
I've updated the README with clearer instructions. Please check and let me know if you're still seeing issues. Closing for now.
